//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkoutRoutines
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyWorkoutRoutinesCtx : DbContext
    {
        public MyWorkoutRoutinesCtx()
            : base("name=MyWorkoutRoutinesCtx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<Routine> Routine { get; set; }
        public virtual DbSet<RoutineExercises> RoutineExercises { get; set; }
        public virtual DbSet<RoutineHistory> RoutineHistory { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
