//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkoutRoutines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routine()
        {
            this.RoutineExercises = new HashSet<RoutineExercises>();
        }
    
        public int RoutineID { get; set; }
        public string RoutineName { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineExercises> RoutineExercises { get; set; }
        public virtual Users Users { get; set; }
    }
}
