//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkoutRoutines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        public int RoutineID { get; set; }
        public string RoutineName { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ExerciseID { get; set; }
    
        public virtual Exercises Exercises { get; set; }
        public virtual Users Users { get; set; }
    }
}
