//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorkoutRoutines
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineHistory
    {
        public int HistoryID { get; set; }
        public int RoutineID { get; set; }
        public Nullable<System.DateTime> DateHistory { get; set; }
    
        public virtual Routine Routine { get; set; }
    }
}
